### ISSUE TITLE
Exceuting the code

### ISSUE THREAD

**Issue by Walid-Ahmed** [TimSC/PyFeatureTrack#1]
How can I run the code on a video file for tracking?

Thanks..

**Comment by TimSC** [comment]
Have you managed to load the video with python? They easiest way is either opencv https://stackoverflow.com/questions/18954889/how-to-process-images-of-a-video-frame-by-frame-in-video-streaming-using-opencv

or pyglet https://bitbucket.org/pyglet/pyglet/wiki/Home
